web/router.ex
defmodule Rumbl.Router do
  use Rumbl.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Rumbl.Auth, repo: Rumbl.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Rumbl do
    pipe_through :browser # Use the default browser stack
  
    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Rumbl do
  #   pipe_through :api
  # end
end

lib/rumbl/endpoint.ex
defmodule Rumbl.Endpoint do
  use Phoenix.Endpoint, otp_app: :rumbl

  socket "/socket", Rumbl.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :rumbl, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_rumbl_key",
    signing_salt: "8fy11r3r"

  plug Rumbl.Router
end

lib/rumbl/repo.ex
defmodule Rumbl.Repo do
  use Ecto.Repo, otp_app: :rumbl
  @moduledoc """
  In memory repository
  """
end

web/models/user.ex
defmodule Rumbl.User do
    use Rumbl.Web, :model
    
    schema "users" do
        field :name, :string 
        field :username, :string
        field :password, :string, virtual: true
        field :password_hash, :string 

        timestamps
    end

    def changeset(model, params \\ :empty) do
        model
        |> cast(params, ~w(name username), [])
        |> validate_length(:username, min: 1, max: 20) 
    end

    def registration_changeset(model, params) do
        model
        |> changeset(params)
        |> cast(params, ~w(password), [])
        |> validate_length(:password, min: 6, max: 100)
        |> put_pass_hash()
    end

    defp put_pass_hash(changeset) do
        case changeset do
         %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
            put_change(changeset, :password_hash, Comeonin.Bcrypt.hashpwsalt(pass))
        _ -> changeset
    end
  end
end

web/controllers/page_controller.ex
defmodule Rumbl.PageController do
  use Rumbl.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/session_controller.ex
defmodule Rumbl.SessionController do
    use Rumbl.Web, :controller

    def new(conn, _) do
        render conn, "new.html"
    end

    def create(conn, %{"session" => %{"username" => user, "password" => pass}}) do

        case Rumbl.Auth.login_by_username_and_pass(conn,user,pass,repo: Repo) do
            
            {:ok, conn} -> 
                conn
                |> put_flash(:info, "Welcome back")
                |> redirect(to: page_path(conn,:index))
            {:error, _reason, conn} ->
                conn
                |> put_flash(:error, "Invalid username/password")
                |> render "new.html"

        end
    end

 def delete(conn, _)  do
     conn
     |> Rumbl.Auth.logout()
     |> redirect(to: page_path(conn, :index))
 end
end

web/controllers/user_controller.ex
defmodule Rumbl.UserController do
    use Rumbl.Web, :controller 
    
    plug :authenticate when action in [:index, :show]

    def index(conn, _params) do
        users = Repo.all(Rumbl.User)
        render conn, "index.html", users: users
    end

    def show(conn, %{"id" => id}) do
        user = Repo.get(Rumbl.User, id)
        render conn, "show.html", user: user
    end

    alias Rumbl.User 
    def new(conn, _params) do
        changeset = User.changeset(%User{})
        render conn, "new.html", changeset: changeset
    end

    def create(conn, %{"user" => user_params}) do
        changeset = User.registration_changeset(%User{}, user_params)
        case Repo.insert(changeset) do
        {:ok, user} ->
        conn
        |> Rumbl.Auth.login(user)
        |> put_flash(:info, "#{user.name} created!")
        |> redirect(to: user_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
        end
    end

    defp authenticate(conn, _opts) do
        if conn.assigns.current_user do
            conn
        else 
            conn 
            |> put_flash(:error, "You must be logged in to access that page")
            |> redirect(to: page_path(conn, :index))
            |> halt()
        end
    end
end

web/views/error_view.ex
defmodule Rumbl.ErrorView do
  use Rumbl.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Rumbl.LayoutView do
  use Rumbl.Web, :view
end

web/views/page_view.ex
defmodule Rumbl.PageView do
  use Rumbl.Web, :view
end

web/views/session_view.ex
defmodule Rumbl.SessionView do
    use Rumbl.Web, :view
end

web/views/user_view.ex
defmodule Rumbl.UserView do
    use Rumbl.Web, :view 
    alias Rumbl.User

    def first_name(%User{ name: name}) do
        name 
        |> String.split(" ")
        |> Enum.at(0) 
    end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Rumbl</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <ol class="breadcrumb text-right">
          <%= if @current_user do %>
            <li><%= @current_user.username %></li>
            <li>
              <%= link "Log out", to: session_path(@conn, :delete, @current_user),
                                  method: "delete" %>
            </li>
          <% else %>
            <li><%= link "Register", to: user_path(@conn, :new) %></li>
            <li><%= link "Log in", to: session_path(@conn, :new) %></li>
          <% end %>
        </ol>
        <span class="logo"></span>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= render @view_module, @view_template, assigns %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/session/new.html.eex
<h1>Login</h1>

<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
  <div class="form-group">
    <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
  </div>
  <%= submit "Log in", class: "btn btn-primary" %>
<% end %>

web/templates/user/index.html.eex
<h1> List of users </h1>

<table class ="table">
<%= for user <- @users do %>
    <tr>
    <td><%= render "user.html", user: user %> </td>
    <td> <%= link "View", to: user_path(@conn, :show, user.id)%></td>
    </tr>
    <% end %> 
</table>

web/templates/user/new.html.eex
<h1>New User</h1>


<%= form_for @changeset, user_path(@conn, :create), fn f -> %>

    <%= if @changeset.action do %>
    <div class="alert alert-danger">
    <p> Oops, something went wrong! Please check the errors below.</p>
    </di>
    <% end %>

  <div class="form-group">
    <%= text_input f, :name, placeholder: "Name", class: "form-control" %>
    <%= error_tag f, :name %>
  </div>
  <div class="form-group">
    <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
    <%= error_tag f, :username %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
    <%= error_tag f, :password %>
  </div>
  <%= submit "Create User", class: "btn btn-primary" %>
<% end %>

web/templates/user/show.html.eex
<h1> Show user info <h1/>
<%= render "user.html", user: @user %> 

web/templates/user/user.html.eex
<b> <%= first_name(@user) %> </b> (<%= @user.id %>) 